// filepath: lib/common/constants/vietnam_locations.dart
import 'package:flutter/material.dart';
import 'package:template/api/plan/dto/getSection.dart';
import 'package:template/common/widgets/tagify_input.dart';

/// Danh sách tất cả tỉnh/thành phố của Việt Nam cho TagifyInput
final List<TagifyItem<SectionItem>> vietnamLocations = [
  TagifyItem<SectionItem>(displayName: 'An Giang', value: const SectionItem(sectionId: '1', sectionName: 'An Giang'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Bà Rịa - Vũng Tàu', value: const SectionItem(sectionId: '2', sectionName: 'Bà Rịa - Vũng Tàu'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Bắc Giang', value: const SectionItem(sectionId: '3', sectionName: 'Bắc Giang'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Bắc Kạn', value: const SectionItem(sectionId: '4', sectionName: 'Bắc Kạn'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Bạc Liêu', value: const SectionItem(sectionId: '5', sectionName: 'Bạc Liêu'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Bắc Ninh', value: const SectionItem(sectionId: '6', sectionName: 'Bắc Ninh'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Bến Tre', value: const SectionItem(sectionId: '7', sectionName: 'Bến Tre'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Bình Định', value: const SectionItem(sectionId: '8', sectionName: 'Bình Định'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Bình Dương', value: const SectionItem(sectionId: '9', sectionName: 'Bình Dương'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Bình Phước', value: const SectionItem(sectionId: '10', sectionName: 'Bình Phước'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Bình Thuận', value: const SectionItem(sectionId: '11', sectionName: 'Bình Thuận'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Cà Mau', value: const SectionItem(sectionId: '12', sectionName: 'Cà Mau'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Cần Thơ', value: const SectionItem(sectionId: '13', sectionName: 'Cần Thơ'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Cao Bằng', value: const SectionItem(sectionId: '14', sectionName: 'Cao Bằng'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Đà Nẵng', value: const SectionItem(sectionId: '15', sectionName: 'Đà Nẵng'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Đắk Lắk', value: const SectionItem(sectionId: '16', sectionName: 'Đắk Lắk'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Đắk Nông', value: const SectionItem(sectionId: '17', sectionName: 'Đắk Nông'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Điện Biên', value: const SectionItem(sectionId: '18', sectionName: 'Điện Biên'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Đồng Nai', value: const SectionItem(sectionId: '19', sectionName: 'Đồng Nai'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Đồng Tháp', value: const SectionItem(sectionId: '20', sectionName: 'Đồng Tháp'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Gia Lai', value: const SectionItem(sectionId: '21', sectionName: 'Gia Lai'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Hà Giang', value: const SectionItem(sectionId: '22', sectionName: 'Hà Giang'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Hà Nam', value: const SectionItem(sectionId: '23', sectionName: 'Hà Nam'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Hà Nội', value: const SectionItem(sectionId: '24', sectionName: 'Hà Nội'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Hà Tĩnh', value: const SectionItem(sectionId: '25', sectionName: 'Hà Tĩnh'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Hải Dương', value: const SectionItem(sectionId: '26', sectionName: 'Hải Dương'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Hải Phòng', value: const SectionItem(sectionId: '27', sectionName: 'Hải Phòng'), icon: Icons.sailing),
  TagifyItem<SectionItem>(displayName: 'Hậu Giang', value: const SectionItem(sectionId: '28', sectionName: 'Hậu Giang'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Hòa Bình', value: const SectionItem(sectionId: '29', sectionName: 'Hòa Bình'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Hưng Yên', value: const SectionItem(sectionId: '30', sectionName: 'Hưng Yên'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Khánh Hòa', value: const SectionItem(sectionId: '31', sectionName: 'Khánh Hòa'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Kiên Giang', value: const SectionItem(sectionId: '32', sectionName: 'Kiên Giang'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Kon Tum', value: const SectionItem(sectionId: '33', sectionName: 'Kon Tum'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Lai Châu', value: const SectionItem(sectionId: '34', sectionName: 'Lai Châu'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Lâm Đồng', value: const SectionItem(sectionId: '35', sectionName: 'Lâm Đồng'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Lạng Sơn', value: const SectionItem(sectionId: '36', sectionName: 'Lạng Sơn'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Lào Cai', value: const SectionItem(sectionId: '37', sectionName: 'Lào Cai'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Long An', value: const SectionItem(sectionId: '38', sectionName: 'Long An'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Nam Định', value: const SectionItem(sectionId: '39', sectionName: 'Nam Định'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Nghệ An', value: const SectionItem(sectionId: '40', sectionName: 'Nghệ An'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Ninh Bình', value: const SectionItem(sectionId: '41', sectionName: 'Ninh Bình'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Ninh Thuận', value: const SectionItem(sectionId: '42', sectionName: 'Ninh Thuận'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Phú Thọ', value: const SectionItem(sectionId: '43', sectionName: 'Phú Thọ'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Phú Yên', value: const SectionItem(sectionId: '44', sectionName: 'Phú Yên'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Quảng Bình', value: const SectionItem(sectionId: '45', sectionName: 'Quảng Bình'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Quảng Nam', value: const SectionItem(sectionId: '46', sectionName: 'Quảng Nam'), icon: Icons.temple_buddhist),
  TagifyItem<SectionItem>(displayName: 'Quảng Ngãi', value: const SectionItem(sectionId: '47', sectionName: 'Quảng Ngãi'), icon: Icons.beach_access),
  TagifyItem<SectionItem>(displayName: 'Quảng Ninh', value: const SectionItem(sectionId: '48', sectionName: 'Quảng Ninh'), icon: Icons.sailing),
  TagifyItem<SectionItem>(displayName: 'Quảng Trị', value: const SectionItem(sectionId: '49', sectionName: 'Quảng Trị'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Sóc Trăng', value: const SectionItem(sectionId: '50', sectionName: 'Sóc Trăng'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Sơn La', value: const SectionItem(sectionId: '51', sectionName: 'Sơn La'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Tây Ninh', value: const SectionItem(sectionId: '52', sectionName: 'Tây Ninh'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Thái Bình', value: const SectionItem(sectionId: '53', sectionName: 'Thái Bình'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Thái Nguyên', value: const SectionItem(sectionId: '54', sectionName: 'Thái Nguyên'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Thanh Hóa', value: const SectionItem(sectionId: '55', sectionName: 'Thanh Hóa'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Thừa Thiên Huế', value: const SectionItem(sectionId: '56', sectionName: 'Thừa Thiên Huế'), icon: Icons.temple_buddhist),
  TagifyItem<SectionItem>(displayName: 'Tiền Giang', value: const SectionItem(sectionId: '57', sectionName: 'Tiền Giang'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'TP. Hồ Chí Minh', value: const SectionItem(sectionId: '58', sectionName: 'TP. Hồ Chí Minh'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Trà Vinh', value: const SectionItem(sectionId: '59', sectionName: 'Trà Vinh'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Tuyên Quang', value: const SectionItem(sectionId: '60', sectionName: 'Tuyên Quang'), icon: Icons.landscape),
  TagifyItem<SectionItem>(displayName: 'Vĩnh Long', value: const SectionItem(sectionId: '61', sectionName: 'Vĩnh Long'), icon: Icons.waves),
  TagifyItem<SectionItem>(displayName: 'Vĩnh Phúc', value: const SectionItem(sectionId: '62', sectionName: 'Vĩnh Phúc'), icon: Icons.location_city),
  TagifyItem<SectionItem>(displayName: 'Yên Bái', value: const SectionItem(sectionId: '63', sectionName: 'Yên Bái'), icon: Icons.landscape),
];

